/**
 * initialize storage
 * instantiate core struct + start networking gRPC server/client
 * start the network server, network client and core in separate threads using tokio::spawn
 */

use std::collections::HashMap;
use std::env;
use std::fs;
use std::net::SocketAddr;
use tonic::transport::Channel;
use tokio::sync::mpsc;
use serde::Deserialize;

// Import your modules
mod core;
mod network;
mod storage;

use core::events::RaftEvent;
use network::server::RaftServerImpl;
use network::pb::raft_server::RaftServer;
use network::pb::raft_client::RaftClient;
use network::client::RaftClientWorker;
use storage::log::UnixWal;

use log::{info};

/// Struct to map the JSON configuration file
#[derive(Deserialize)]
struct ClusterConfig {
    nodes: HashMap<u64, String>,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {

    // initialize logger
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();

    // 1. Read cmd-line args and parse JSON config file 
    let args: Vec<String> = env::args().collect();
    if args.len() < 3 {
        eprintln!("Usage: {} <NODE_ID> <CONFIG_PATH>", args[0]);
        std::process::exit(1);
    }

    let my_id: u64 = args[1].parse().expect("Node ID must be an integer");
    let config_path = &args[2];

    let config_data = fs::read_to_string(config_path)
        .expect("Failed to read configuration file");
    let config: ClusterConfig = serde_json::from_str(&config_data)
        .expect("Failed to parse JSON config");

    let my_listen_addr_str = config.nodes.get(&my_id)
        .unwrap_or_else(|| panic!("Node ID {} was not found in the config file!", my_id));
    let my_listen_addr: SocketAddr = my_listen_addr_str.parse()?;

    let mut peer_configs = HashMap::new();
    for (&node_id, address) in &config.nodes {
        if node_id != my_id {
            // Tonic requires the "http://" prefix for its URIs
            peer_configs.insert(node_id, format!("http://{}", address));
        }
    }

    // 2. Instantiate the MPSC Communication Channels
    let (inbound_tx, inbound_rx) = mpsc::channel(100);
    let (outbound_tx, outbound_rx) = mpsc::channel(100);

    // 3. Connect to peers and build the RaftClients map
    let mut peers_map = HashMap::new();
    for (peer_id, peer_address) in peer_configs {
        // we need to manually specify a fairly small timeout for each request (i.e. 100ms) so that the 
        // micro-retries in the network layer don't take too long
        let endpoint = Channel::from_shared(peer_address)?
            .connect_timeout(std::time::Duration::from_millis(50)) // Timeout for the initial TCP handshake
            .timeout(std::time::Duration::from_millis(100));               // Max time allowed for ANY single RPC request
        
        // Connect lazily. Tonic won't actually hit the network until the first RPC is sent.
        // This is CRITICAL because if Node 2 is down on startup, Node 1 won't crash!
        let channel = endpoint.connect_lazy();
        
        // Create the actual gRPC client wrapper generated by Tonic
        let client = RaftClient::new(channel);
        peers_map.insert(peer_id, client);
    }

    let peer_ids = peers_map.keys().copied().collect();

    // 4. Initialize Team Member 1's Client Worker with the connected clients
    let client_worker = RaftClientWorker::new(outbound_rx, peers_map);    

    // 5. Initialize Team Member 1's Server Implementation
    let server_impl = RaftServerImpl::new(inbound_tx.clone());


    // 6. Initialize storage
    let storage_path = format!("raft_data_{}", my_id);
    let storage = Box::new(UnixWal::new(&storage_path)
        .expect("Failed to initialize storage"));

    // 7. Initialize Team Member 3's Core Logic Loop
    // (You would pass Team Member 2's storage engine in here as well)
    let cloned_tx = inbound_tx.clone();
    let mut core_loop =
        core::RaftCore::new_with_config(inbound_rx, inbound_tx, outbound_tx, my_id, peer_ids, storage);

    // 8. Spawn background execution tasks
    
    // Task A: Outbound Client worker
    tokio::spawn(async move {
        client_worker.run().await;
    });

    // Task B: Pure Core Logic State Machine
    tokio::spawn(async move {
        core_loop.run().await;
    });

    // spawn heartbeat tick worker
    let heartbeat_tx = cloned_tx;
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_millis(50));
        
        loop {
            interval.tick().await; // Blocks non-blockingly for 50ms
            
            if heartbeat_tx.send(RaftEvent::HeartbeatTick).await.is_err() {
                break;
            }
        }
    });

    // Task C: Inbound gRPC Server (Blocks the main thread, keeping the app alive)
    // println!("Raft Node {} listening on {}", my_id, my_listen_addr);
    info!("Raft Node {} listening on {}", my_id, my_listen_addr);
    tonic::transport::Server::builder()
        .add_service(RaftServer::new(server_impl))
        .serve(my_listen_addr)
        .await?;

    Ok(())
}
