/**
 * initialize storage
 * instantiate core struct + start networking gRPC server/client
 * start the network server, network client and core in separate threads using tokio::spawn
 */


use std::collections::HashMap;
use std::net::SocketAddr;
use tonic::transport::Channel;
use tokio::sync::mpsc;

// Import your modules
mod core;
mod network;

use network::server::RaftServerImpl;
use network::pb::raft_server::RaftServer;
use network::pb::raft_client::RaftClient;
use network::client::RaftClientWorker;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // 1. Setup mock configuration (In production, load this from a file or CLI args)
    let my_id: u64 = 1;
    let my_listen_addr: SocketAddr = "[::1]:50051".parse()?;
    
    // Hardcoded peer definitions: Node ID -> IP/Port String
    let mut peer_configs = HashMap::new();
    peer_configs.insert(2, "http://[::1]:50052".to_string());
    peer_configs.insert(3, "http://[::1]:50053".to_string());

    // 2. Instantiate the MPSC Communication Channels
    let (inbound_tx, inbound_rx) = mpsc::channel(100);
    let (outbound_tx, outbound_rx) = mpsc::channel(100);

    // 3. Connect to peers and build the RaftClients map
    let mut peers_map = HashMap::new();
    for (peer_id, peer_address) in peer_configs {
        // we need to manually specify a fairly small timeout for each request (i.e. 100ms) so that the 
        // micro-retries in the network layer don't take too long
        let endpoint = Channel::from_shared(peer_address)?
            .connect_timeout(std::time::Duration::from_millis(50)) // Timeout for the initial TCP handshake
            .timeout(std::time::Duration::from_millis(100));               // Max time allowed for ANY single RPC request
        
        // Connect lazily. Tonic won't actually hit the network until the first RPC is sent.
        // This is CRITICAL because if Node 2 is down on startup, Node 1 won't crash!
        let channel = endpoint.connect_lazy();
        
        // Create the actual gRPC client wrapper generated by Tonic
        let client = RaftClient::new(channel);
        peers_map.insert(peer_id, client);
    }

    // 4. Initialize Team Member 1's Client Worker with the connected clients
    let client_worker = RaftClientWorker::new(outbound_rx, peers_map);

    // 5. Initialize Team Member 1's Server Implementation
    let server_impl = RaftServerImpl::new(inbound_tx);

    // 6. Initialize Team Member 3's Core Logic Loop
    // (You would pass Team Member 2's storage engine in here as well)
    let mut core_loop = core::RaftCore::new(inbound_rx, outbound_tx);

    // 7. Spawn background execution tasks
    
    // Task A: Outbound Client worker
    tokio::spawn(async move {
        client_worker.run().await;
    });

    // Task B: Pure Core Logic State Machine
    tokio::spawn(async move {
        core_loop.run().await;
    });

    // Task C: Inbound gRPC Server (Blocks the main thread, keeping the app alive)
    println!("Raft Node {} listening on {}", my_id, my_listen_addr);
    tonic::transport::Server::builder()
        .add_service(RaftServer::new(server_impl))
        .serve(my_listen_addr)
        .await?;

    Ok(())
}
